<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Whoop.Sdk.Samples.TrustedPartner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Whoop.Sdk.Extensions.DependencyInjection/Whoop.Sdk.Extensions.DependencyInjection.csproj" />
  </ItemGroup>

</Project>
